package com.benabdallah.csvpipeline.adapter.postgres;
import com.benabdallah.csvpipeline.application.port.out.*; import com.benabdallah.csvpipeline.upload.*; import java.sql.ResultSet; import java.sql.SQLException; import java.sql.Timestamp; import java.util.*; import org.springframework.jdbc.core.simple.JdbcClient;
public final class JdbcUploadAdapter implements UploadRepository,IdempotencyRepository,OutboxRepository {
 private final JdbcClient jdbc; public JdbcUploadAdapter(JdbcClient jdbc){this.jdbc=jdbc;}
 public void save(Upload u){jdbc.sql("INSERT INTO csv_upload(id,file_name,content_type,size_bytes,sha256,object_key,status,attempt_count,updated_at) VALUES(:id,:name,:type,:size,:sha,:key,:status,:attempts,:updated)").param("id",u.id().value()).param("name",u.fileName()).param("type",u.contentType()).param("size",u.sizeBytes()).param("sha",u.sha256()).param("key",u.objectKey()).param("status",u.status().name()).param("attempts",u.attemptCount()).param("updated",Timestamp.from(u.updatedAt())).update();}
 public Optional<Upload> find(UploadId id){return query("SELECT * FROM csv_upload WHERE id=:id",id);}
 public Optional<Upload> findForUpdate(UploadId id){return query("SELECT * FROM csv_upload WHERE id=:id FOR UPDATE",id);}
 private Optional<Upload> query(String sql,UploadId id){return jdbc.sql(sql).param("id",id.value()).query((rs,n)->map(rs)).optional();}
 public void update(Upload u){jdbc.sql("UPDATE csv_upload SET status=:status,attempt_count=:attempts,third_party_reference=:ref,failure_code=:failure,updated_at=:updated WHERE id=:id").param("status",u.status().name()).param("attempts",u.attemptCount()).param("ref",u.thirdPartyReference()).param("failure",u.failureCode()).param("updated",Timestamp.from(u.updatedAt())).param("id",u.id().value()).update();}
 private Upload map(ResultSet r)throws SQLException{return Upload.restore(new UploadId(r.getObject("id",UUID.class)),r.getString("file_name"),r.getString("content_type"),r.getLong("size_bytes"),r.getString("sha256"),r.getString("object_key"),UploadStatus.valueOf(r.getString("status")),r.getInt("attempt_count"),r.getString("third_party_reference"),r.getString("failure_code"),r.getTimestamp("updated_at").toInstant());}
 public Optional<IdempotencyRecord> find(String operation,String key){return jdbc.sql("SELECT operation,idempotency_key,request_hash,upload_id FROM http_idempotency WHERE operation=:operation AND idempotency_key=:key").param("operation",operation).param("key",key).query((r,n)->new IdempotencyRecord(r.getString(1),r.getString(2),r.getString(3),new UploadId(r.getObject(4,UUID.class)))).optional();}
 public void save(IdempotencyRecord r){jdbc.sql("INSERT INTO http_idempotency(operation,idempotency_key,request_hash,upload_id) VALUES(:operation,:key,:hash,:upload)").param("operation",r.operation()).param("key",r.key()).param("hash",r.requestHash()).param("upload",r.uploadId().value()).update();}
 public void appendUploadReady(UploadId id){UUID eventId=UUID.randomUUID();String payload="{\"eventId\":\""+eventId+"\",\"uploadId\":\""+id+"\",\"schemaVersion\":1}";jdbc.sql("INSERT INTO outbox_event(id,aggregate_id,event_type,payload) VALUES(:id,:aggregate,'CsvUploadReady',CAST(:payload AS jsonb)) ON CONFLICT(aggregate_id,event_type) DO NOTHING").param("id",eventId).param("aggregate",id.value()).param("payload",payload).update();}
}
