package com.benabdallah.csvpipeline.worker;
import tools.jackson.databind.*; import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.MediaType; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.kafka.annotation.KafkaListener; import org.springframework.kafka.support.Acknowledgment; import org.springframework.stereotype.Component; import org.springframework.web.client.RestClient; import software.amazon.awssdk.regions.Region; import software.amazon.awssdk.services.s3.*; import software.amazon.awssdk.services.s3.model.GetObjectRequest;
@Component public class CsvUploadListener {
 private final JdbcClient jdbc;private final ObjectMapper json;private final S3Client s3;private final RestClient thirdParty;private final String bucket;
 CsvUploadListener(JdbcClient jdbc,ObjectMapper json,@Value("${pipeline.s3.region}")String region,@Value("${pipeline.s3.bucket}")String bucket,@Value("${pipeline.third-party.url}")String url){this.jdbc=jdbc;this.json=json;this.bucket=bucket;this.s3=S3Client.builder().region(Region.of(region)).build();this.thirdParty=RestClient.builder().baseUrl(url).build();}
 @KafkaListener(topics="${pipeline.kafka.topic:csv-upload-ready.v1}",groupId="csv-processing-worker") public void onMessage(String payload,Acknowledgment ack)throws Exception {var root=json.readTree(payload);UUID eventId=UUID.fromString(root.get("eventId").asText());UUID uploadId=UUID.fromString(root.get("uploadId").asText());int inserted=jdbc.sql("INSERT INTO consumer_inbox(consumer_name,event_id,state,attempts,lease_until) VALUES('csv-worker',:event,'PROCESSING',1,now()+interval '5 minutes') ON CONFLICT DO NOTHING").param("event",eventId).update();if(inserted==0){String state=jdbc.sql("SELECT state FROM consumer_inbox WHERE consumer_name='csv-worker' AND event_id=:event").param("event",eventId).query(String.class).single();if(state.equals("COMPLETED")){ack.acknowledge();return;}}
  var row=jdbc.sql("UPDATE csv_upload SET status='PROCESSING',attempt_count=attempt_count+1,updated_at=now() WHERE id=:id AND status IN ('READY','RETRY_PENDING') RETURNING object_key").param("id",uploadId).query(String.class).optional();if(row.isEmpty())return;
  try(var stream=s3.getObject(GetObjectRequest.builder().bucket(bucket).key(row.get()).build())){validate(stream);var response=thirdParty.post().uri("/api/v1/imports").header("Idempotency-Key",uploadId.toString()).contentType(MediaType.APPLICATION_JSON).body(Map.of("uploadId",uploadId)).retrieve().body(ImportResponse.class);jdbc.sql("UPDATE csv_upload SET status='SUCCEEDED',third_party_reference=:ref,updated_at=now() WHERE id=:id").param("ref",response.reference()).param("id",uploadId).update();jdbc.sql("UPDATE consumer_inbox SET state='COMPLETED',completed_at=now(),lease_until=NULL WHERE consumer_name='csv-worker' AND event_id=:event").param("event",eventId).update();ack.acknowledge();}catch(IllegalArgumentException permanent){jdbc.sql("UPDATE csv_upload SET status='FAILED',failure_code='INVALID_CSV',updated_at=now() WHERE id=:id").param("id",uploadId).update();jdbc.sql("UPDATE consumer_inbox SET state='COMPLETED',completed_at=now() WHERE consumer_name='csv-worker' AND event_id=:event").param("event",eventId).update();ack.acknowledge();}catch(Exception transientFailure){jdbc.sql("UPDATE csv_upload SET status='RETRY_PENDING',failure_code='THIRD_PARTY_UNAVAILABLE',next_attempt_at=now()+interval '10 seconds',updated_at=now() WHERE id=:id").param("id",uploadId).update();throw transientFailure;}}
 static void validate(InputStream input)throws IOException {try(var reader=new BufferedReader(new InputStreamReader(input,StandardCharsets.UTF_8))){String header=reader.readLine();if(header==null||!header.contains(","))throw new IllegalArgumentException("CSV header is required");long rows=0;String line;while((line=reader.readLine())!=null){if(++rows>1_000_000||line.length()>100_000)throw new IllegalArgumentException("CSV limit exceeded");}}}
 record ImportResponse(String reference){}
}
